#!/usr/bin/env bash
# Read-only: which env settings each WorkmateIQ service is missing in production (names only, never values).
# Compared against the .env.example files on the feature branch. Many keys are optional; read the output with that in mind.
cd /opt/workmateiq/services || exit 1
check() { local s=$1; shift; local m=""; for k in "$@"; do grep -q "^$k=." "$s/.env" 2>/dev/null || m="$m $k"; done; echo "$s: ${m:-all present}"; }
check communication-service SERVICE_NAME PORT NODE_ENV MONGODB_URL PUBLIC_BASE_URL AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_REGION AWS_SESSION_TOKEN SQS_QUEUE_URL AWS_ENDPOINT_URL EMAIL_MODE RESEND_API_KEY GMAIL_USER GMAIL_APP_PASSWORD DEFAULT_FROM_EMAIL WHATSAPP_MODE WHATSAPP_PHONE_NUMBER_ID WHATSAPP_ACCESS_TOKEN INCOMING_SERVICE_KEYS SERVICE_PERMISSIONS
check auth-service SERVICE_NAME PORT NODE_ENV MONGODB_URL ACCESS_TOKEN_SECRET REFRESH_TOKEN_SECRET FIREBASE_PROJECT_ID SEED_ADMIN_EMAIL SEED_ADMIN_PASSWORD INCOMING_SERVICE_KEYS SERVICE_PERMISSIONS
check api-gateway SERVICE_NAME PORT NODE_ENV ALLOWED_ORIGINS AUTH_SERVICE_URL REGISTRATION_SERVICE_URL FORM_SERVICE_URL ONBOARDING_SERVICE_URL CLIENT_SERVICE_URL COMMUNICATION_SERVICE_URL DASHBOARD_SERVICE_URL ENQUIRY_SERVICE_URL
check onboarding-service SERVICE_NAME PORT NODE_ENV MONGODB_URL ACCESS_TOKEN_SECRET CLIENT_LOGIN_URL CAPTCHA_SECRET AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_REGION AWS_SESSION_TOKEN S3_BUCKET_NAME S3_ENDPOINT S3_FORCE_PATH_STYLE FORM_SERVICE_URL CLIENT_SERVICE_URL AUTH_SERVICE_URL COMMUNICATION_SERVICE_URL FORM_SERVICE_API_KEY CLIENT_SERVICE_API_KEY AUTH_SERVICE_API_KEY COMMUNICATION_SERVICE_API_KEY INCOMING_SERVICE_KEYS SERVICE_PERMISSIONS
